#!/usr/bin/env ruby

require 'rake/testtask'
require 'rake/rdoctask'
require 'rake/clean'

task :default => [:test]

Rake::TestTask.new do |t|
    t.libs << "test"
    t.verbose = true
end

Rake::RDocTask.new do |rd|
    rd.main = "README"
    rd.rdoc_files.include("README", "lib/**/*.rb")
    system('scp -r -C html/* dm1@shell.berlios.de:/home/groups/ri18n/htdocs/rdoc')
end